# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- "*"

stages:
  - stage: Build
    jobs:
      - job: 'validateandtest'
        pool:
          vmimage: "vs2017-win2016"
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'Visual Studio Ultimate with MSDN(1)(8f925446-95ce-4346-a2d8-009a22c2f698)'
            subscriptionId: '8f925446-95ce-4346-a2d8-009a22c2f698'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'task-rg-01'
            location: 'UK South'
            templateLocation: 'URL of the file'
            csmFileLink: 'https://raw.githubusercontent.com/devsheoran/scripts/master/azuredeploy.simplehubspoketopology.json'
            overrideParameters: '-vmAdminUsername adminuser -vmAdminPassword p2ssword@123 -subscriptionId 8f925446-95ce-4346-a2d8-009a22c2f698 -dnsIdentifier ntc.com'
            deploymentMode: 'Incremental'
            deploymentOutputs: '$var=ConvertFrom-Json ''$(vmAdminUsername)'' $var.vmAdminUsername.value'
          
            
                
             