# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- "*"

stages:
  - stage: Build
    condition: 
      and(succeeded(), eq(variables['State'], 'Sandbox'))
    jobs:
      - job: 'validateandtest'
        pool:
          vmimage: "vs2017-win2016"
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'Visual Studio Ultimate with MSDN(1)(8f925446-95ce-4346-a2d8-009a22c2f698)'
            subscriptionId: '8f925446-95ce-4346-a2d8-009a22c2f698'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'test-rg-01'
            location: 'UK South'
            templateLocation: 'URL of the file'
            csmFileLink: 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-1vm-2nics-2subnets-1vnet/azuredeploy.json'
            overrideParameters: '-adminUsername adminuser -adminPassword p2ssword@123'
            deploymentMode: 'Complete'
            deploymentOutputs: '$var=ConvertFrom-Json ''$(adminUsername)'' ; $var.adminUsername.value'
  - stage: CleanUp
    condition: (and(succeeded), eq(variables['State'], 'Clean'))
    jobs:
      - job: clean
        pool:
          vmimage: "vs2017-win2016"
        steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'Visual Studio Ultimate with MSDN(2)(8f925446-95ce-4346-a2d8-009a22c2f698)'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: 'az group delete --name test-rg-01 --yes'
                
             